[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CUP"
authors = [{name = "Cheng Li", email = "chengcli@umich.edu"}]
dynamic = ["version", "description"]
